### ISSUE TITLE
שגיאה בשמירת קובץ גיבוי עם שם בעברית

### ISSUE THREAD

**Issue by miki932** [teamThevibe/skin.eminence.zeev#2]
כאשר מנסים לבצע גיבוי, המערכת לא מאפשרת את שמירת קובץ הגיבוי בשם בעברית, אלא רק באנגלית.
![default](https://cloud.githubusercontent.com/assets/8677745/14228091/3063f4d2-f914-11e5-8bd2-9f79cca1546f.PNG)

**Comment by teamThevibe** [comment]
היי , לא מדובר בבאג מאחר ואפשר להשתמש אך ורק במספרים ואותיות באנגלית .
